name: Log ENV

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
    inputs:
      log:
        description: 'Log'
        required: false
        default: 'true'

env:
  GLOBAL_WORKFLOW_ENV: __Global Env Val__

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV var
        run: |
          echo "CUSTOM_VAR=IT WORKS" >> $GITHUB_ENV
          echo "CUSTOM_VAR_MULTY<<EOF" >> $GITHUB_ENV
          echo "Multiline Var: line1" >> $GITHUB_ENV
          echo "Multiline Var: line2" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Use ENV var via `env` block
        run: |
          echo $CUSTOM_VAR # OK
          echo ${{ env.CUSTOM_VAR }} # OK
          echo $USE_CUSTOM_VAR # NOT OK, prints ''
          echo ${{ env.USE_CUSTOM_VAR }} # NOT OK, prints ''
          echo $USE_CUSTOM_VAR_2 # NOT OK, prints '$CUSTOM_VAR'
          echo ${{ env.USE_CUSTOM_VAR_2 }} # OK
          echo $USE_CUSTOM_VAR_3 # NOT OK, prints '$GLOBAL_WORKFLOW_ENV'
          echo ${{ env.USE_CUSTOM_VAR_3 }} # OK
        env:
          USE_CUSTOM_VAR: ${{ env.CUSTOM_VAR }}
          USE_CUSTOM_VAR_2: $CUSTOM_VAR
          USE_CUSTOM_VAR_3: $GLOBAL_WORKFLOW_ENV

      - name: Use ENV var via `env` block in external action
        uses: 'easingthemes/simple-github-action@main'
        env:
          USE_CUSTOM_VAR: ${{ env.CUSTOM_VAR }} #
          USE_CUSTOM_VAR_2: $CUSTOM_VAR # NOT OK, prints '$CUSTOM_VAR'
          USE_CUSTOM_VAR_3: $GLOBAL_WORKFLOW_ENV #
          USE_CUSTOM_VAR_MULTY: ${{ env.CUSTOM_VAR_MULTY }}
